name: flutter_callkeep_example
description: Demonstrates how to use the flutter_callkeep plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  

  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  http: ^0.13.4
  flutter_callkeep: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/test.png
